# to test different docker builds
volumes:
  bird-data:
    # external: true
services:
  api:
    container_name: api
    build:
      context: ./api/app
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      - ./api/app:/app
    environment:
      VERSION: prod
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
  ghi:
    container_name: ghi
    build:
      context: ./ghi/app
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./ghi/app:/app
      - ./ghi/app/node_modules:/node_modules
    ports:
      - 80:80
    depends_on:
      - api
  db:
    image: postgres:13.3-alpine
    container_name: db
    platform: linux/amd64
    volumes:
      - bird-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
