volumes:
  bird-data:
    # external: true
services:
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      WAIT_HOST: db:5432
      PORT: 8000:8000
    depends_on:
      - db
  ghi:
    build:
      context: ./ghi/app
      dockerfile: Dockerfile
    # working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - 80:80
    depends_on:
      - api
    # environment:
    #   NODE_ENV: production
    # environment:
    #   HOST_OS: ${OS}
      # NODE_ENV: development
      # HOST: "0.0.0.0"
      # PUBLIC_URL: http://localhost:3000
  db:
    image: postgres:13.3-alpine
    container_name: db
    volumes:
      - bird-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
