
FROM node:lts-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /nginx/nginx.conf /etc/nginx/conf.d/default.conf
